//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSRSWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemMapping
    {
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
        public int no_of_renting_days { get; set; }
        public int orderitemmapping_id { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual Product Product { get; set; }
    }
}
