//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSRSWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string nameOnCard { get; set; }
        public Nullable<int> cardNumber { get; set; }
        public Nullable<int> cvv { get; set; }
        public string netbankingName { get; set; }
        public int paymentid { get; set; }
        public int order_id { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
