//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSRSWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int paymentid { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public Nullable<double> amount { get; set; }
        public int transactionsid { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
